### PR TITLE
#352 removes the sightings plugin - to be replaced with a standard bi…

### PR DESCRIPTION
**Pull request by m-r-c**
…ocollect project activity form

### CODE REVIEW

**Comment by temi** [comment]
PB - form is complete. called species sightings

**Comment by adam-collins** [comment]
https://github.com/AtlasOfLivingAustralia/ecodata/tree/removeSightings
https://upsource.ala.org.au/ecodata/review/ECODATA-CR-44

https://github.com/AtlasOfLivingAustralia/biocollect/tree/removeSightings
https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-127

**Comment by javier-molina** [comment]
@sat01a , @temi  could you an of you please test creating a new record for the new single sightings form?

It works for @adam-collins  but everytime I create a new record, an additional attachments sections appears on screen and with that a JS error

image

image

I have started with a fresh clone fro both ecodata and biocollect and still same result, see above for the branches you need to use.

thanks

**Comment by javier-molina** [comment]
When using a file with invalid inputs (records from other forms) parsing errors appear directly on screen. It would be better to keep those in logs while just displaying a generic error on screen, it could be as simple as the json displayed when records are processed correctly.


image

**Comment by javier-molina** [comment]
Form now works for me as in test and major review comments have been addressed.

**Pull request merged**
