### PR TITLE
Feature/verification

### PR DESCRIPTION
**Pull request by magdziarek**
Documentation: https://github.com/biodiversitydata-se/biocollect/wiki/Admin-functionality

### CODE REVIEW

**Comment by temi** [comment]
@magdziarek I could not see code that enables verification on survey setting. Not sure if I missed it. Also, how is facet hidden if it is `adminOnly`?

**Comment by magdziarek** [comment]
@temi sorry, I realized when I was moving commits to the new branch I missed some. I will check it again on Monday. For now I added the logic behind hiding adminOnly facets in the latest commit 2543a9474375cfe18a31c30e379ac6d9610b3601
Also, updated ecodata with changes relevant to this feature and issued a PR on ecodata.

**Comment by temi** [comment]
Thanks @magdziarek ! That looks good to me. BTW, do you have any test cases for these changes?

**Comment by magdziarek** [comment]
@temi Only what I posted in the documentation in our wiki. What exactly would be good to have?

**Comment by magdziarek** [comment]
Hey @temi - is the below sufficient? Let me know if this is not what you needed.

**Configure a Project Activity to allow the admins for manual verification of submitted by users activities**

As a user with the role ALA admin or userPermission “Admin” for Test Project:
1. Open a test project that is projectType: “survey” and isCitizenScience: true 
2. From project admin tab > Survey settings. Select your Test Survey from the dropdown. Open the tab Survey Info. 
3. For the Test Survey tick the boxes “Allow admins to perform manual verification” and “Show verification status to volunteers”. Save changes.
5. Open Admin > Manage Hubs {biocollectServerURL}/{hub}/admin/manageHubs
6. Edit the hub that the above modified Test Project belongs to: open Facets tab. Use Configure facets on all records page. Add verificationStatusFacet and tick the box “Admin only”. Save changes.

→ expected outcome is that whenever you add records to this survey a verificationStatus value should be assigned. On default it should be “not verified”. When activities that belong to this survey  are opened in admin mode (ALA, FC admin or project admin) the dropdown with available status value should be visible. When a regular user, member of the project, opens the activity, they should see a green (approved) or red (anything else than approved) badge to the right representing the status of the activity. 
→ When records are displayed in All Records view, Status facet will be available and records can be filtered using that facet.  

------------------------------------------- 
**Submit records to a survey which has the verification feature enabled**

1. From a user account with userPermission role Editor for this Test Project, open the Test Project page and try to add data to the Test Survey form. Save changes.

→ expected  outcome: a new activity is created with verificationStatus: “not verified”
→ this activity can only be viewed by this user and users with admin permissions

-----------------------------------------------------

**Approve records submitted by project members of the project**
As a user with the role ALA admin or userPermission “Admin” for Test Project 
1. Open All Records from the top menu.
2. Using the facets menu on the left, filter the records to see the one that has status with value “not verified”. Open it in Edit mode.
3. From the dropdown menu select status “Approved”. Save changes. 

→ expected  outcome: the activity’s verificationStatus is changed to “approved”. When opened in index mode, the activity has a green badge in the top right corner. 
→ The activity can be viewed by anyone

**Comment by temi** [comment]
@magdziarek Thank for that. Sorry for the mis-understanding. My question was about unit tests. Do you have any javascript unit test cases for the new feature? We are trying to improve the test coverage in BioCollect. Therefore, trying our best to include unit tests for new features.

**Comment by magdziarek** [comment]
@temi , no, sorry, I don't have any unit tests for this

**Comment by djtfmartin** [comment]
@pbrenton  @temi is there any update on the progress for this PR ?
this was discussed last week at the SBDI meeting.
I guess this a related PR: https://github.com/AtlasOfLivingAustralia/ecodata/pull/679

**Comment by temi** [comment]
@djtfmartin we need to do some testing on this. Our aim now is to get it merged in 6.3.

**Review by temi — APPROVED** [review]

**Comment by temi** [comment]
cherry picked to feature/swedish branch and merged with develop

**Pull request merged**
